raise Exception('It\'s an Exception')
